<?php
declare(strict_types=1);

/**
 * Auto-generated Maestro extension manifest.
 * DO NOT EDIT - This file is regenerated by composer.
 *
 * Run `php bin/maestro maestro discover` to regenerate.
 */

return array (
  0 => 
  array (
    'package' => 'neuron-core/maestro',
    'class' => 'NeuronCore\\Maestro\\Extension\\Core\\CoreExtension',
    'enabled' => true,
  ),
  1 => 
  array (
    'package' => 'neuron-core/maestro',
    'class' => 'NeuronCore\\Maestro\\Extension\\Coding\\CodingExtension',
    'enabled' => true,
  ),
);
